name: BuzzAnalysis
channels:
  - conda-forge
dependencies:
  - python=3.13
  - numpy
  - pandas
  - scipy
  - shapely>=2
  - pyarrow
  - tqdm
  - matplotlib
  - pyside6
  - pyqtgraph
  - pillow
  - opencv
  - labelme
  - pytest
